CREATE DATABASE vendas_sucos

CREATE DATABASE vendas_sucos2 DEFAULT CHARACTER SET UTF8; 

CREATE DATABASE IF NOT exists vendas_sucos2;

DROP DATABASE IF EXISTS vendas_sucos2;

USE vendas_sucos;

CREATE TABLE PRODUTO
(CODIGO VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL, 
PRECO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO));

CREATE TABLE VENDEDORES 
(MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
COMISSAO FLOAT NULL,
DATA_ADIMISSAO DATE NULL,
FERIA BIT(10) NULL,
PRIMARY KEY (MATRICULA));

ALTER TABLE VENDEDORES RENAME COLUMN DATA_ADIMISSAO TO DATA_ADMISSAO;

USE vendas_sucos;

CREATE TABLE TABELA_DE_VENDAS
(NUMERO VARCHAR(5) NOT NULL,
DATA_VENDA DATE NULL,
CPF VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPOSTO FLOAT NULL,
PRIMARY KEY (NUMERO));

ALTER TABLE TABELA_DE_VENDAS ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);

ALTER TABLE TABELA_DE_VENDAS ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);

USE vendas_sucos;

ALTER TABLE tabela_de_vendas RENAME Notas;

USE vendas_sucos;

CREATE TABLE itens_notas;
(NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
QUANTIDADE INT, 
PRECO FLOAT,
PRIMARY KEY (NUMERO, CODIGO));

ALTER TABLE itens_notas ADD CONSTRAINT FK_NOTAS
FOREIGN KEY (NUMERO),
REFERENCES NOTAS (NUMERO);

ALTER TABLE itens_notas ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO)
REFERENCES PRODUTOS (CODIGO);

USE vendas_sucos;

INSERT INT PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMABALAGEM, PRECO_LISTA)
VALUES ('1040107', 'Light - 350 ml - Melância', 'melância', '350 ml', 'Lata', 4.56);

SELECT * FROM PRODUTOS;

INSERT INT PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMABALAGEM, PRECO_LISTA)
VALUES ('1040108', 'Light - 350 ml - Graviola', 'Graviola', '350 ml', 'Lata', 4.00);

INSERT INT PRODUTOS
VALUES ('1040109', 'Light - 350 ml - Açai', 'Açai', '350 ml', 'Lata', 5.60);

INSERT INT PRODUTOS
VALUES ('1040110', 'Light - 350 ml - Jaca', 'Jaca', '350 ml', 'Lata', 6.00),
       ('1040111', 'Light - 350 ml - Manga', 'Manga', '350 ml', 'Lata', 3.50);

USE vendas_sucos;

SELECT * FROM sucos_vendas.tabela_de_produtos;

SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, 
EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA AS PRECO_LISTA
FROM sucos_vendas.tabela_de_produtos;
WHERE CODIGO_DO_PRODUTO NOT IN (SELECT CODIGO FROM produtos);

INSERT INTO produtos ()
SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, 
SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA
FROM sucos_vendas.tabela_de_produtos;
WHERE CODIGO_DO_PRODUTO NOT IN (SELECT CODIGO FROM produtos);

SELECT * FROM produtos;

USE vendas_sucos;

SELECT * FROM clientes;

SELECT * FROM sucos_vendas.tabela_de_clientes;

SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, 
DATA_DE_NASCIMENTO AS DATA_NASCIMENTO, IDADE, SEXO, LIMITE_DE_CREDTO AS LIMITE_CREDITO,
VOLUME_DE_COMPRA AS VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM sucos_vendas.tabela_de_clientes WHERE CPF
NOT IN (SELECT CPF FROM CLIENTES);

INSERT INTO CLIENTES
SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, 
DATA_DE_NASCIMENTO AS DATA_NASCIMENTO, IDADE, SEXO, LIMITE_DE_CREDTO AS LIMITE_CREDITO,
VOLUME_DE_COMPRA AS VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM sucos_vendas.tabela_de_clientes WHERE CPF
NOT IN (SELECT CPF FROM CLIENTES);

SELECT * FROM CLIENTES;

SELECT * FROM vendedores

SELECT * FROM produtos

UPDATE produtos SET PRECO_LISTA = 5 WHERE CODIGO = '1000889';

UPDATE proutos SET EMBALAGEM = 'PET', TAMANHO = '1 LITRO', DESCRITOR =
'SABOR DA MONTANHA - 1 LITRO - UVA' WHERE CODIGO = '1000889';

SELECT * FROM produtos WHERE SABOR = 'Maracujá'; 

UPDATE produtos SET PRECO_LISTA = PRECO_LISTA * 1.10 WHERE SABOR = 'Maracujá';

SELECT * FROM VENDEDORES;

SELECT * FROM SUCOS_VENDAS.TABELA_DE_VENDEDORES;

SELECT * FROM VENDEDORES A
INNER JOIN SUCOS_VENDAS.TABELA_DE_VENDEDORES B
ON A.MATRICULA = SUBSTRING(B.MATRICULA,3,3)

UPDATE VENDEDORES A INNER JOIN SUCOS_VENDAS.TABELA_DE_VENDEDORES B
ON A.MATRICULA = SUBSTRING(B.MATRICULA,3,3)
SET A.FERIAS = B.DE_FERIAS;

INSERT INTO PRODUTOS (CODIGO,DESCRITOR,SABOR,TAMANHO,EMABALAGEM,PRECO_LISTA)
   VALUES ('1001001','Sabor dos Alpes 700 ml - Manga','Manga','700 ml','Garrafa',7.50),
   ('1001000','Sabor dos Alpes 700 ml - Melão','Melão','700 ml','Garrafa',7.50),
   ('1001002','Sabor dos Alpes 700 ml - Graviola','Graviola','700 ml','Garrafa',7.50),
   ('1001003','Sabor dos Alpes 700 ml - Tangerina','Tangerina','700 ml','Garrafa',7.50),
   ('1001004','Sabor dos Alpes 700 ml - Abacate','Abacate','700 ml','Garrafa',7.50),
   ('1001005','Sabor dos Alpes 700 ml - Açai','Açai','700 ml','Garrafa',7.50),
   ('1001006','Sabor dos Alpes 1 Litro - Manga','Manga','1 Litro','Garrafa',7.50),
   ('1001007','Sabor dos Alpes 1 Litro - Melão','Melão','1 Litro','Garrafa',7.50),
   ('1001008','Sabor dos Alpes 1 Litro - Graviola','Graviola','1 Litro','Garrafa',7.50),
   ('1001009','Sabor dos Alpes 1 Litro - Tangerina','Tangerina','1 Litro','Garrafa',7.50),
   ('1001010','Sabor dos Alpes 1 Litro - Abacate','Abacate','1 Litro','Garrafa',7.50),
   ('1001011','Sabor dos Alpes 1 Litro - Açai','Açai','1 Litro','Garrafa',7.50);

   SELECT * FROM PRODUTOS WHERE SUBSTRING(DESCRITOR,1,15) = 'Sabor dos Alpes';

   DELETE FROM PRODUTOS WHERE CODIGO = '1001000';

   DELETE FROM PRODUTOS WHERE TAMANHO = '1 Litro'
   AND SUBSTRING(DESCRITOR,1,15) = 'Sabor dos Alpes';

   SELECT CODIGO_DO_PRODUTO FROM SUCOS_VENDAS.TABELA_DE_PRODUTOS;

   SELECT CODIGO FROM PRODUTOS WHERE 
   CODIGO NOT IN (SELECT CODIGO_DO_PRODUTO FROM SUCOS_VENDAS.TABELA_DE_PRODUTOS);

   DELETE FROM PRODUTOS WHERE 
   CODIGO NOT IN (SELECT CODIGO_DO_PRODUTO FROM SUCOS_VENDAS.TABELA_DE_PRODUTOS);

CREATE TABLE 'produtos2' (
   'CODIGO' varchar(10) NOT NULL,
   'DESCRITOR' varchar(100) DEFAULT NULL,
   'SABOR' varchar(50) DEFAULT NULL,
   'TAMANHO' varchar(50) DEFAULT NULL,
   'EMBALAGEM' varchar(50) DEFAULT NULL,
   'PRECO_LISTA' float DEFAULT NULL,
   PRIMARY KEY ('CODIGO')
) ;

SELECT * FROM produtos2;

INSERT INTO produto2
SELECT * FROM produto;

UPDATE produto2 SET preco_lista = 8;

DELETE FROM produtos2;

START TRANSACTION;

SELECT * FROM VENDEDORES;

UPDATE VENDEDORES SET COMISSAO = COMISSAO * 1.15;

ROLLBACK;

COMMIT;

START TRANSACTION;

INSERT INTO 'vendas_sucos'.'vendedores'
('MATRICULA',
'NOME',
'BAIRRO',
'COMISSAO',
'DATA_ADMISSAO',
'FERIAS')
VALUES
('999999',
'JOAO DA SILVA',
'Icaraí',
0.08,
'2012-01-15',
0);

UPDATE VENDEDORES SET COMISSAO = COMISSAO * 1.15;

INSERT INTO 'vendas_sucos'.'vendedores'
('MATRICULA',
'NOME',
'BAIRRO',
'COMISSAO',
'DATA_ADMISSAO',
'FERIAS')
VALUES
('999998',
'JOAO DA SILVA2',
'Icaraí',
0.08,
'2012-01-15',
0);

ROLLBACK;

COMMIT;